# Generated by Django 4.0.2 on 2022-03-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creator_id', models.IntegerField()),
                ('active', models.BooleanField()),
                ('content', models.JSONField()),
            ],
        ),
    ]
