# Generated by Django 4.0.2 on 2022-03-03 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('creator_id', models.IntegerField()),
                ('code', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('passcode', models.CharField(max_length=255)),
                ('chance', models.BooleanField()),
                ('chance_game', models.CharField(max_length=50)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('weight', models.IntegerField()),
                ('dest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='backend.question')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='backend.question')),
            ],
        ),
    ]
