# Generated by Django 4.0.2 on 2022-03-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_game_question_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='game_id',
            new_name='game',
        ),
    ]
