# Generated by Django 4.0.2 on 2022-03-01 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
