# Generated by Django 4.0.2 on 2022-03-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_game_code'),
        ('backend', '0004_rename_game_id_question_game'),
    ]

    operations = [
    ]
