# Generated by Django 4.0.2 on 2022-03-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_merge_20220307_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='content',
        ),
    ]
