# Generated by Django 4.0.2 on 2022-03-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_gamemode_gamesession_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
