# Generated by Django 4.0.2 on 2022-03-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_question_chance_game'),
        ('backend', '0006_alter_gamesession_end_time'),
    ]

    operations = [
    ]
