# Generated by Django 4.0.2 on 2022-03-11 01:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_20220311_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('option_chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.option')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team')),
            ],
        ),
    ]
