# Generated by Django 4.0.2 on 2022-03-11 17:32

import backend.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_gamesession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='updated_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='updated_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='option',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
