# Generated by Django 4.0.2 on 2022-03-17 16:58

import backend.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_gamemode_created_at_gamemode_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', backend.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('updated_at', backend.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('option_chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.option')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team')),
            ],
        ),
    ]
