# Generated by Django 4.0.2 on 2022-03-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_gamesessionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
    ]
