# Generated by Django 4.0.2 on 2022-03-17 22:57

import backend.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_team_created_at_remove_team_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=backend.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
