# Generated by Django 4.0.2 on 2022-03-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_team_created_at_remove_team_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessionanswer',
            name='time',
        ),
    ]
