# Generated by Django 4.0.2 on 2022-03-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_team_created_at_team_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessionanswer',
            name='time',
        ),
    ]
