# Generated by Django 4.0.2 on 2022-03-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_merge_20220318_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('section', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('number', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
