# Generated by Django 4.0.2 on 2022-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_game_created_at_alter_gamemode_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='No Semester Set', max_length=32),
        ),
    ]
