# Generated by Django 4.0.2 on 2022-04-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessionanswer',
            name='passcode_entered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesessionanswer',
            name='option_chosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.option'),
        ),
    ]
