# Generated by Django 4.0.2 on 2022-04-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_contexthelp'),
        ('backend', '0017_gamesessionanswer_passcode_entered_and_more'),
    ]

    operations = [
    ]
