# Generated by Django 4.0.2 on 2022-04-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_gamesession_active'),
        ('backend', '0018_merge_20220408_1933'),
    ]

    operations = [
    ]
