# Generated by Django 4.0.2 on 2022-04-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_merge_20220408_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexthelp',
            name='questions',
            field=models.ManyToManyField(default=None, to='backend.Question'),
        ),
    ]
