# Generated by Django 4.0.2 on 2022-04-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_contexthelp_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
