# Generated by Django 4.0.2 on 2022-04-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_gamesession_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.course'),
        ),
    ]
