# Generated by Django 4.0.2 on 2022-04-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_course_active_alter_contexthelp_questions'),
        ('backend', '0021_gamesession_course'),
    ]

    operations = [
    ]
