# Generated by Django 4.0.2 on 2022-04-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_merge_20220422_1748'),
        ('backend', '0022_merge_20220422_1828'),
    ]

    operations = [
    ]
