# Generated by Django 4.0.4 on 2022-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_merge_20220425_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='location',
            field=models.CharField(default='SC122', max_length=50),
        ),
    ]
