image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Initialize Django
      python3 -m pip install -r ./backend/requirements.txt &&
      python3 ./backend/manage.py migrate
      # Initialize react
      pushd . &&
      cd frontend &&
      npm install &&
      popd
    command: |
      echo 'TODO: start app'
  - name: Set k8s context
    command: echo $K8S_CTX | base64 -d > ~/.kube/config
