image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Initialize Django
      python3 -m pip install -r ./backend/requirements.txt &&
      python3 ./backend/manage.py migrate
      # Initialize react
      pushd . &&
      cd frontend &&
      npm install &&
      popd
      # Initialize selenium
      sudo apt-get update
      sudo apt-get install libnss3-dev xvfb -y
      sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
      sudo touch /etc/apt/sources.list.d/google-chrome.list
      sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      sudo apt-get -y update
      sudo apt-get -y install google-chrome-stable
    command: |
      echo 'TODO: start app'
  - name: Set k8s context
    command: echo $K8S_CTX | base64 -d > ~/.kube/config
