version: "0.1.0"

services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/ethicsAdventure/django-static
    env_file:
      - .env
    depends_on:
      - db
  
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/ethicsAdventure/django-static
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  static_volume: {}