version: "0.1.0"

services:
  db:
    image: postgres
    volumes:
      - /ea/data/db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - local

  backend:
    restart: unless-stopped
    image: ${EA_REGISTRY}/backend:0.1.0
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/server/django_static
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - local
  
  frontend:
    restart: unless-stopped
    image: ${EA_REGISTRY}/frontend:0.1.0
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/server/django_static
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - local
      - default

volumes:
  static_volume: {}

networks:
  local:
    internal: true
    name: internal-network