version: "3.8"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - static_volume:/app/ethicsAdventure/django-static
    env_file:
      - .env
  
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/ethicsAdventure/django-static
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  static_volume: {}