name: Django cd

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        if: github.event.pull_request.merged
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure AWS
        uses: aws-actions/configure-aws-credntials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build and push docker image
        env:
          EA_REGISTRY: ${{ secrets.EA_REGISTRY }}
        run: make push-backend
