name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    env:
      EA_BACKEND_SECRET: 'ci-secret-Qn0fWgYDE1c0J0suhr7rLqfQe7nMC5aG'
      EA_MODE: 'dev'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get -y update
        sudo apt-get remove libpq5
        sudo apt-get install libpq-dev -y
        make install-backend

    - name: Run Tests
      run: make test-backend

    - name: Build coverage file
      run: |
        coverage run --source='.' manage.py test
        coverage report > backend_coverage.txt
