name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
          node-version: 16

    - name: NPM Cache
      uses: actions/cache@v2
      with:
        path: "frontend/node_modules"
        key: node-modules-${{ hashFiles('frontend/package.json') }}

    - name: Test & Upload Results
      uses: artiomtr/jest-coverage-report-action@v2
      if: github.event_name == 'pull_request'
      with:
        working-directory: ./frontend
        test-script: npm test
        coverage-file: ./report.json
        base-coverage-file: ./report.json
