name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    # runs-on: self-hosted
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
          node-version: 16

    - name: NPM Cache
      uses: actions/cache@v2
      with:
        path: "frontend/node_modules"
        key: node-modules-${{ hashFiles('frontend/package.json') }}

    - run: npm ci
      working-directory: ./frontend

    - name: Generate Coverage
      working-directory: ./frontend
      run: |
        npm install
        npm run test -- --coverage --watchAll=false

    - name: Upload main coverage artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        working-directory: ./frontend
        name: main-react-coverage
        path: ./coverage/coverage-final.json

    # - name: Download main coverage artifact
    #   if: github.event_name == 'pull_request'
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: main-react-coverage
    #     working-directory: ./frontend
    #     path: ./coverage/main-coverage-final.json

    - name: Upload Results
      uses: ArtiomTr/jest-coverage-report-action@v2.0.6
      if: github.event_name == 'pull_request'
      with:
        working-directory: ./frontend
        coverage-file: ./coverage/coverage-final.json
        base-coverage-file: ./coverage/coverage-final.json
        skip-step: install