name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: NPM Cache
      uses: actions/cache@v2
      with:
        path: "frontend/node_modules"
        key: node-modules-${{ hashFiles('frontend/package.json') }}

    - run: npm ci
      working-directory: ./frontend

    - run: npm ci
      working-directory: ./frontend

    - name: Run Tests
      run: make test-frontend
